version: '3'

services:
  react-app:	
    image: reactApp:latest	
    deploy:
      restart_policy:
        condition: "any"
        delay: "0"
        max_attempts: 3
        window: "30s"	
    ports: 	
      - "8080"	
    networks:	
      - web	
      - default	
    labels:	
      - "traefik.docker.network=web"	
      - "traefik.enable=true"	
      - "traefik.reactboilerplate.frontend.rule=Host:reactApp.yourdomain.com"
      - "traefik.reactboilerplate.frontend.port=8080"
      - "traefik.reactboilerplate.frontend.protocol=http"

networks:
  web:
    external: 
      name: web